### ISSUE TITLE
Add LEARN.md

### ISSUE THREAD

**Issue by ericdrosado** [amandp13/Cool-Scripts-Python-Nerds#86]
`Learn` repos should have a LEARN.md file to teach another student how to build your project step by step. Your repo doesn't quite fit the typical `Learn` repo, but that doesn't mean you can't add a LEARN.md 😄 . If you are still interested in having your repo classified as a `Learn` repo, I would recommend a little lesson on a particular script or perhaps there is something else you would like to teach?

You can teach with code snippets, images, or even short (5 minute) long video lessons. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

**Comment by amandp13** [comment]
Hi @ericdrosado, As I can see that there is a file **Contribution.md** file to help/teach another student how to build the project step by step. 
Do let me know if I got you wrong.

**Comment by ericdrosado** [comment]
My apologies for the confusion @amandp13. When I use the word "build" I am referring to teaching a student how to write code. In your case, your repo is a collection of scripts, and each script has an explanation and sometimes there are examples. Effectively, every script directory and file you have is essentially a LEARN.md. 

The problem we'll have is that in order to classify your repo as a `learn` repo, we will need to add a LEARN.md file. In another repo that signed up for CX, they are using a [table of contents](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/Learn.md) in their LEARN.md since all of their content is dedicated to learning. Perhaps that could be a solution for your repo? What do you think?

**Comment by amandp13** [comment]
Oh! Thank you for this clarification @ericdrosado, now I understood, so it would be great it this repo would be a **collaborated** repo instead of **learn** as this repo is a collection of scripts and code and students are free to collaborate anything which they find unique and interesting, so the only thing which they need is already mentioned in the [Contribution.md ](https://github.com/amandp13/Cool-Scripts-Python-Nerds/blob/master/Contribution.md) file i.e. how to start an open source contribution and the step to step guide.
And thank you for sharing this [table of contents](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/Learn.md), let me add this in my repo too, this would be really helpful for others.

**Comment by amandp13** [comment]
I have added learn.md file.

**Comment by ericdrosado** [comment]
@amandp13 since your repo will be a `collaborate` repo, you do not need the `LEARN.md`. I recommend removing it 😄

**Comment by amandp13** [comment]
Okay if you say then let's remove that.
